<div class="page-content row">  
  <div class="page-header"> <!-- Page header -->
    <div class="page-title">
      <h3> <?php echo  $pageTitle ;?> <small><?php echo $pageNote ;?></small></h3>
    </div>    
    
    <ul class="breadcrumb">
      <li><a href="<?php echo site_url('') ?>"> <?php echo $this->lang->line('core.home'); ?></a></li>
      <li><a href="<?php echo site_url('sximo/config/getHelp') ?>"> Help</a></li>
      <li class="active"> Developer </li>
    </ul>      
      
  </div><!-- /Page header -->

   <div class="page-content-wrapper m-t">
     <div class="row">
        <div class="col-md-4">
          <?php $this->load->view('sximo/config/manual/developersidebar'); ?>
        </div>

        <div class="col-md-8" style="margin-bottom:50px;">
          <h2> Model Structure </h2>
          <p> Every Model generated by code builder will have same structure and code</p>
          <h4> Model code </h4>
          <pre class="prettyprint">
              class ModuleModel extends SB_Model {
                  
                  public $table = 'table';
                  public $primaryKey = 'key';

                  public function __construct() {
                    parent::__construct();
                    
                  }

                  public static function querySelect()
                  {                                                   
                    return " SELECT table.* FROM table ";
                  }
                  public static function queryWhere()
                  {                          
                    return " WHERE table.key IS NOT NULL ";
                  }
                  
                  public static function queryGroup()
                  {
                    return "  ";
                  }
                  
              }
          </pre>
        </div>
     </div>
   </div><!-- page-content-wrapper -->

</div> <!-- /page-content-row -->